name: ti3h_k1_jawara
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.2
  riverpod_lint: ^2.6.4
  auto_size_text: ^3.0.0

flutter:

  uses-material-design: true

